# Generated by Django 4.1.3 on 2022-11-25 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='post',
            name='short_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
